//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.23 at 04:12:02 PM KST 
//


package org.isotc211._2005.gmd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.isotc211._2005.gco.DecimalPropertyType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy;
import org.jvnet.jaxb2_commons.lang.CopyTo;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Geographic area of the entire dataset referenced to WGS 84
 * 
 * <p>Java class for EX_GeographicBoundingBox_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EX_GeographicBoundingBox_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gmd}AbstractEX_GeographicExtent_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="westBoundLongitude" type="{http://www.isotc211.org/2005/gco}Decimal_PropertyType"/&gt;
 *         &lt;element name="eastBoundLongitude" type="{http://www.isotc211.org/2005/gco}Decimal_PropertyType"/&gt;
 *         &lt;element name="southBoundLatitude" type="{http://www.isotc211.org/2005/gco}Decimal_PropertyType"/&gt;
 *         &lt;element name="northBoundLatitude" type="{http://www.isotc211.org/2005/gco}Decimal_PropertyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EX_GeographicBoundingBox_Type", propOrder = {
    "westBoundLongitude",
    "eastBoundLongitude",
    "southBoundLatitude",
    "northBoundLatitude"
})
public class EXGeographicBoundingBoxType
    extends AbstractEXGeographicExtentType
    implements Cloneable, CopyTo, Equals, HashCode, ToString
{

    @XmlElement(required = true)
    protected DecimalPropertyType westBoundLongitude;
    @XmlElement(required = true)
    protected DecimalPropertyType eastBoundLongitude;
    @XmlElement(required = true)
    protected DecimalPropertyType southBoundLatitude;
    @XmlElement(required = true)
    protected DecimalPropertyType northBoundLatitude;

    /**
     * Gets the value of the westBoundLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalPropertyType }
     *     
     */
    public DecimalPropertyType getWestBoundLongitude() {
        return westBoundLongitude;
    }

    /**
     * Sets the value of the westBoundLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalPropertyType }
     *     
     */
    public void setWestBoundLongitude(DecimalPropertyType value) {
        this.westBoundLongitude = value;
    }

    /**
     * Gets the value of the eastBoundLongitude property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalPropertyType }
     *     
     */
    public DecimalPropertyType getEastBoundLongitude() {
        return eastBoundLongitude;
    }

    /**
     * Sets the value of the eastBoundLongitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalPropertyType }
     *     
     */
    public void setEastBoundLongitude(DecimalPropertyType value) {
        this.eastBoundLongitude = value;
    }

    /**
     * Gets the value of the southBoundLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalPropertyType }
     *     
     */
    public DecimalPropertyType getSouthBoundLatitude() {
        return southBoundLatitude;
    }

    /**
     * Sets the value of the southBoundLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalPropertyType }
     *     
     */
    public void setSouthBoundLatitude(DecimalPropertyType value) {
        this.southBoundLatitude = value;
    }

    /**
     * Gets the value of the northBoundLatitude property.
     * 
     * @return
     *     possible object is
     *     {@link DecimalPropertyType }
     *     
     */
    public DecimalPropertyType getNorthBoundLatitude() {
        return northBoundLatitude;
    }

    /**
     * Sets the value of the northBoundLatitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecimalPropertyType }
     *     
     */
    public void setNorthBoundLatitude(DecimalPropertyType value) {
        this.northBoundLatitude = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            DecimalPropertyType theWestBoundLongitude;
            theWestBoundLongitude = this.getWestBoundLongitude();
            strategy.appendField(locator, this, "westBoundLongitude", buffer, theWestBoundLongitude);
        }
        {
            DecimalPropertyType theEastBoundLongitude;
            theEastBoundLongitude = this.getEastBoundLongitude();
            strategy.appendField(locator, this, "eastBoundLongitude", buffer, theEastBoundLongitude);
        }
        {
            DecimalPropertyType theSouthBoundLatitude;
            theSouthBoundLatitude = this.getSouthBoundLatitude();
            strategy.appendField(locator, this, "southBoundLatitude", buffer, theSouthBoundLatitude);
        }
        {
            DecimalPropertyType theNorthBoundLatitude;
            theNorthBoundLatitude = this.getNorthBoundLatitude();
            strategy.appendField(locator, this, "northBoundLatitude", buffer, theNorthBoundLatitude);
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof EXGeographicBoundingBoxType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final EXGeographicBoundingBoxType that = ((EXGeographicBoundingBoxType) object);
        {
            DecimalPropertyType lhsWestBoundLongitude;
            lhsWestBoundLongitude = this.getWestBoundLongitude();
            DecimalPropertyType rhsWestBoundLongitude;
            rhsWestBoundLongitude = that.getWestBoundLongitude();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "westBoundLongitude", lhsWestBoundLongitude), LocatorUtils.property(thatLocator, "westBoundLongitude", rhsWestBoundLongitude), lhsWestBoundLongitude, rhsWestBoundLongitude)) {
                return false;
            }
        }
        {
            DecimalPropertyType lhsEastBoundLongitude;
            lhsEastBoundLongitude = this.getEastBoundLongitude();
            DecimalPropertyType rhsEastBoundLongitude;
            rhsEastBoundLongitude = that.getEastBoundLongitude();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "eastBoundLongitude", lhsEastBoundLongitude), LocatorUtils.property(thatLocator, "eastBoundLongitude", rhsEastBoundLongitude), lhsEastBoundLongitude, rhsEastBoundLongitude)) {
                return false;
            }
        }
        {
            DecimalPropertyType lhsSouthBoundLatitude;
            lhsSouthBoundLatitude = this.getSouthBoundLatitude();
            DecimalPropertyType rhsSouthBoundLatitude;
            rhsSouthBoundLatitude = that.getSouthBoundLatitude();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "southBoundLatitude", lhsSouthBoundLatitude), LocatorUtils.property(thatLocator, "southBoundLatitude", rhsSouthBoundLatitude), lhsSouthBoundLatitude, rhsSouthBoundLatitude)) {
                return false;
            }
        }
        {
            DecimalPropertyType lhsNorthBoundLatitude;
            lhsNorthBoundLatitude = this.getNorthBoundLatitude();
            DecimalPropertyType rhsNorthBoundLatitude;
            rhsNorthBoundLatitude = that.getNorthBoundLatitude();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "northBoundLatitude", lhsNorthBoundLatitude), LocatorUtils.property(thatLocator, "northBoundLatitude", rhsNorthBoundLatitude), lhsNorthBoundLatitude, rhsNorthBoundLatitude)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            DecimalPropertyType theWestBoundLongitude;
            theWestBoundLongitude = this.getWestBoundLongitude();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "westBoundLongitude", theWestBoundLongitude), currentHashCode, theWestBoundLongitude);
        }
        {
            DecimalPropertyType theEastBoundLongitude;
            theEastBoundLongitude = this.getEastBoundLongitude();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "eastBoundLongitude", theEastBoundLongitude), currentHashCode, theEastBoundLongitude);
        }
        {
            DecimalPropertyType theSouthBoundLatitude;
            theSouthBoundLatitude = this.getSouthBoundLatitude();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "southBoundLatitude", theSouthBoundLatitude), currentHashCode, theSouthBoundLatitude);
        }
        {
            DecimalPropertyType theNorthBoundLatitude;
            theNorthBoundLatitude = this.getNorthBoundLatitude();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "northBoundLatitude", theNorthBoundLatitude), currentHashCode, theNorthBoundLatitude);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof EXGeographicBoundingBoxType) {
            final EXGeographicBoundingBoxType copy = ((EXGeographicBoundingBoxType) draftCopy);
            if (this.westBoundLongitude!= null) {
                DecimalPropertyType sourceWestBoundLongitude;
                sourceWestBoundLongitude = this.getWestBoundLongitude();
                DecimalPropertyType copyWestBoundLongitude = ((DecimalPropertyType) strategy.copy(LocatorUtils.property(locator, "westBoundLongitude", sourceWestBoundLongitude), sourceWestBoundLongitude));
                copy.setWestBoundLongitude(copyWestBoundLongitude);
            } else {
                copy.westBoundLongitude = null;
            }
            if (this.eastBoundLongitude!= null) {
                DecimalPropertyType sourceEastBoundLongitude;
                sourceEastBoundLongitude = this.getEastBoundLongitude();
                DecimalPropertyType copyEastBoundLongitude = ((DecimalPropertyType) strategy.copy(LocatorUtils.property(locator, "eastBoundLongitude", sourceEastBoundLongitude), sourceEastBoundLongitude));
                copy.setEastBoundLongitude(copyEastBoundLongitude);
            } else {
                copy.eastBoundLongitude = null;
            }
            if (this.southBoundLatitude!= null) {
                DecimalPropertyType sourceSouthBoundLatitude;
                sourceSouthBoundLatitude = this.getSouthBoundLatitude();
                DecimalPropertyType copySouthBoundLatitude = ((DecimalPropertyType) strategy.copy(LocatorUtils.property(locator, "southBoundLatitude", sourceSouthBoundLatitude), sourceSouthBoundLatitude));
                copy.setSouthBoundLatitude(copySouthBoundLatitude);
            } else {
                copy.southBoundLatitude = null;
            }
            if (this.northBoundLatitude!= null) {
                DecimalPropertyType sourceNorthBoundLatitude;
                sourceNorthBoundLatitude = this.getNorthBoundLatitude();
                DecimalPropertyType copyNorthBoundLatitude = ((DecimalPropertyType) strategy.copy(LocatorUtils.property(locator, "northBoundLatitude", sourceNorthBoundLatitude), sourceNorthBoundLatitude));
                copy.setNorthBoundLatitude(copyNorthBoundLatitude);
            } else {
                copy.northBoundLatitude = null;
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new EXGeographicBoundingBoxType();
    }

}
