//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.23 at 04:12:02 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.isotc211.org/2005/gco", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.isotc211._2005.gco;
